---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/uk-pdc/metadata-infrastructure/metadata-standards:0.1.0-alpine
    command: ['watch']
    volumes:
      - ./gulpfile.js:/usr/src/app/gulpfile.js
      - ./iso-19115:/usr/src/app/data/iso-19115
      - ./assets:/usr/src/app/assets
      - ./public:/usr/src/app/public

  web:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./assets:/usr/share/nginx/html/public/assets
      - ./public:/usr/share/nginx/html/public/records
      - ./index.html:/usr/share/nginx/html/public/index.html
    ports:
      - "9000:9000"
