---
version: '3.8'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/uk-pdc/metadata-infrastructure/metadata-standards:latest-alpine
    working_dir: /usr/src/app/site
    volumes:
      - ./site:/usr/src/app/site
    ports:
      - "9000:9000"
